import { TouristPlace, PlaceCategory } from '../types/planner';
import { LocationCoordinates } from '../types/location';
import { haversineDistance, resolveDestinationType, filterAttractionsForDestination } from './geoValidationService';

// ---------------------------------------------------------------------------
// CURATED TOURIST PLACES — each entry has VERIFIED lat/lng coordinates.
// getPlacesForDestination() filters by DISTANCE, not by name string,
// so unrelated city attractions are always geographically rejected.
// ---------------------------------------------------------------------------
export const CURATED_TOURIST_PLACES: TouristPlace[] = [

  // ─── KOLKATA (22.5726°N, 88.3639°E) ────────────────────────────────────
  {
    id: 'kol-victoria-memorial',
    destinationId: 'kolkata',
    cityName: 'Kolkata',
    name: 'Victoria Memorial',
    category: 'history',
    description: 'Iconic marble monument dedicated to Queen Victoria, surrounded by lush manicured gardens and reflecting pools.',
    whyVisit: 'Houses magnificent British colonial artifacts, royal portraits, historical galleries, and serene outdoor gardens.',
    image: 'https://images.unsplash.com/photo-1558431382-27e303142255?auto=format&fit=crop&w=800&q=80',
    coordinates: { lat: 22.5448, lng: 88.3426 },
    approxDurationMinutes: 120,
    bestTimeToVisit: 'Morning',
    openingHours: '10:00 AM',
    closingHours: '05:00 PM',
    estimatedTicketPrice: '₹50 (Indians) / ₹500 (Foreigners)',
    isIndoor: false,
    distanceFromBaseKm: 2.1,
  },
  {
    id: 'kol-howrah-bridge',
    destinationId: 'kolkata',
    cityName: 'Kolkata',
    name: 'Howrah Bridge (Rabindra Setu)',
    category: 'culture',
    description: 'World-famous balanced cantilever bridge over the Hooghly River connecting Kolkata and Howrah.',
    whyVisit: 'An architectural marvel carrying over 100,000 vehicles daily, offering stunning sunset river views.',
    image: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=800&q=80',
    coordinates: { lat: 22.5851, lng: 88.3468 },
    approxDurationMinutes: 45,
    bestTimeToVisit: 'Evening',
    openingHours: 'Open 24 Hours',
    closingHours: 'Open 24 Hours',
    estimatedTicketPrice: 'Free Entry',
    isIndoor: false,
    distanceFromBaseKm: 4.8,
  },
  {
    id: 'kol-indian-museum',
    destinationId: 'kolkata',
    cityName: 'Kolkata',
    name: 'Indian Museum',
    category: 'history',
    description: 'The ninth oldest museum in the world and the largest in India, featuring rare antiquities and Egyptian mummies.',
    whyVisit: 'Explore rare fossil skeletons, ancient Buddhist stupa relics, Mughal paintings, and geological treasures.',
    image: 'https://images.unsplash.com/photo-1566127444979-b3d2b654e3d7?auto=format&fit=crop&w=800&q=80',
    coordinates: { lat: 22.5579, lng: 88.3511 },
    approxDurationMinutes: 150,
    bestTimeToVisit: 'Afternoon',
    openingHours: '10:00 AM',
    closingHours: '05:00 PM',
    estimatedTicketPrice: '₹50',
    isIndoor: true,
    distanceFromBaseKm: 1.5,
  },
  {
    id: 'kol-st-pauls-cathedral',
    destinationId: 'kolkata',
    cityName: 'Kolkata',
    name: "St. Paul's Cathedral",
    category: 'culture',
    description: 'Anglican cathedral of Indo-Gothic architecture known for its tranquil atmosphere and stained glass windows.',
    whyVisit: 'Beautiful quiet sanctuary featuring Florentine frescoes, historical monuments, and quiet gardens.',
    image: 'https://images.unsplash.com/photo-1548625149-fc4a29cf7092?auto=format&fit=crop&w=800&q=80',
    coordinates: { lat: 22.5442, lng: 88.3463 },
    approxDurationMinutes: 45,
    bestTimeToVisit: 'Morning',
    openingHours: '09:00 AM',
    closingHours: '05:00 PM',
    estimatedTicketPrice: 'Free Entry',
    isIndoor: true,
    distanceFromBaseKm: 2.3,
  },
  {
    id: 'kol-prinsep-ghat',
    destinationId: 'kolkata',
    cityName: 'Kolkata',
    name: 'Prinsep Ghat',
    category: 'photography',
    description: 'Historic riverfront ghat built during the British Raj, famous for boat rides and street food.',
    whyVisit: 'Enjoy scenic traditional wooden boat rides on the Hooghly at golden hour with views of the illuminated cable bridge.',
    image: 'https://images.unsplash.com/photo-1608979048467-315ef9229f3a?auto=format&fit=crop&w=800&q=80',
    coordinates: { lat: 22.5564, lng: 88.3328 },
    approxDurationMinutes: 90,
    bestTimeToVisit: 'Evening',
    openingHours: 'Open 24 Hours',
    closingHours: 'Open 24 Hours',
    estimatedTicketPrice: 'Free Entry (Boat ride ₹200–₹400)',
    isIndoor: false,
    distanceFromBaseKm: 3.2,
  },
  {
    id: 'kol-park-street-food',
    destinationId: 'kolkata',
    cityName: 'Kolkata',
    name: 'Park Street Culinary & Heritage Walk',
    category: 'food',
    description: "Kolkata's legendary dining corridor lined with historic restaurants like Mocambo, Peter Cat, and Flurys.",
    whyVisit: 'Taste iconic Chelo Kebabs, heritage cakes, Kathi rolls, and experience vibrant evening nightlife.',
    image: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80',
    coordinates: { lat: 22.5539, lng: 88.3524 },
    approxDurationMinutes: 120,
    bestTimeToVisit: 'Evening',
    openingHours: '11:00 AM',
    closingHours: '11:00 PM',
    estimatedTicketPrice: 'Variable Food Costs (~₹400–₹1000)',
    isIndoor: true,
    distanceFromBaseKm: 1.2,
  },
  {
    id: 'kol-science-city',
    destinationId: 'kolkata',
    cityName: 'Kolkata',
    name: 'Science City Kolkata',
    category: 'family',
    description: 'The largest science center in the Indian subcontinent featuring a Space Odyssey, 3D theater, and cable car rides.',
    whyVisit: 'Interactive science exhibits, dinosaur enclave, space simulator, and family-friendly outdoor parks.',
    image: 'https://images.unsplash.com/photo-1507676184212-d03ab07a01bf?auto=format&fit=crop&w=800&q=80',
    coordinates: { lat: 22.5401, lng: 88.3953 },
    approxDurationMinutes: 180,
    bestTimeToVisit: 'Afternoon',
    openingHours: '09:00 AM',
    closingHours: '07:00 PM',
    estimatedTicketPrice: '₹60 base entry',
    isIndoor: true,
    distanceFromBaseKm: 6.5,
  },
  {
    id: 'kol-eco-park',
    destinationId: 'kolkata',
    cityName: 'Kolkata',
    name: 'Eco Urban Park (New Town)',
    category: 'nature',
    description: 'Sprawling 480-acre urban park featuring a large central lake, 7 Wonders replicas, and butterfly gardens.',
    whyVisit: 'Boating, cycling paths, miniature replicas of World Wonders, and serene lakeside green space.',
    image: 'https://images.unsplash.com/photo-1519331379826-f10be5486c6f?auto=format&fit=crop&w=800&q=80',
    coordinates: { lat: 22.5975, lng: 88.4682 },
    approxDurationMinutes: 180,
    bestTimeToVisit: 'Evening',
    openingHours: '02:30 PM',
    closingHours: '08:30 PM',
    estimatedTicketPrice: '₹30 entry',
    isIndoor: false,
    distanceFromBaseKm: 14.2,
  },
  {
    id: 'kol-kalighat-temple',
    destinationId: 'kolkata',
    cityName: 'Kolkata',
    name: 'Kalighat Kali Temple',
    category: 'religious',
    description: 'One of the 51 Shakti Peethas and the most sacred Kali temple in Bengal, giving Kolkata its name.',
    whyVisit: 'Experience profound spiritual atmosphere, ancient rituals, and the deeply cultural devotion of Bengali pilgrims.',
    image: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=800&q=80',
    coordinates: { lat: 22.5189, lng: 88.3454 },
    approxDurationMinutes: 60,
    bestTimeToVisit: 'Morning',
    openingHours: '05:00 AM',
    closingHours: '10:30 PM',
    estimatedTicketPrice: 'Free Entry (Offerings voluntary)',
    isIndoor: false,
    distanceFromBaseKm: 5.5,
  },
  {
    id: 'kol-college-street',
    destinationId: 'kolkata',
    cityName: 'Kolkata',
    name: 'College Street Book Market',
    category: 'culture',
    description: "World's largest second-hand book market stretching along College Street near Presidency University.",
    whyVisit: 'Browse lakhs of rare Bengali and English books, academic titles, and vintage publications at bargain prices.',
    image: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?auto=format&fit=crop&w=800&q=80',
    coordinates: { lat: 22.5784, lng: 88.3638 },
    approxDurationMinutes: 90,
    bestTimeToVisit: 'Morning',
    openingHours: '09:00 AM',
    closingHours: '07:00 PM',
    estimatedTicketPrice: 'Free Entry (Books from ₹10)',
    isIndoor: false,
    distanceFromBaseKm: 3.8,
  },

  // ─── JAIPUR (26.9124°N, 75.7873°E) ─────────────────────────────────────
  {
    id: 'jpr-amber-fort',
    destinationId: 'jaipur',
    cityName: 'Jaipur',
    name: 'Amer Fort (Amber Palace)',
    category: 'history',
    description: 'Majestic hilltop fortress made of yellow and pink sandstone overlooking Maota Lake.',
    whyVisit: 'Exquisite Sheesh Mahal (Mirror Palace), grand courtyards, subterranean passages, and light shows.',
    image: 'https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=800&q=80',
    coordinates: { lat: 26.9855, lng: 75.8513 },
    approxDurationMinutes: 150,
    bestTimeToVisit: 'Morning',
    openingHours: '08:00 AM',
    closingHours: '05:30 PM',
    estimatedTicketPrice: '₹100 (Indians) / ₹500 (Foreigners)',
    isIndoor: false,
    distanceFromBaseKm: 11.0,
  },
  {
    id: 'jpr-hawa-mahal',
    destinationId: 'jaipur',
    cityName: 'Jaipur',
    name: 'Hawa Mahal (Palace of Winds)',
    category: 'photography',
    description: 'Five-story pink sandstone palace with 953 intricate jharokhas (small lattice windows).',
    whyVisit: 'Stunning Rajput architecture designed for royal women to observe street festivals undetected.',
    image: 'https://images.unsplash.com/photo-1603262110263-fb0112e7cc33?auto=format&fit=crop&w=800&q=80',
    coordinates: { lat: 26.9239, lng: 75.8267 },
    approxDurationMinutes: 60,
    bestTimeToVisit: 'Morning',
    openingHours: '09:00 AM',
    closingHours: '05:00 PM',
    estimatedTicketPrice: '₹50',
    isIndoor: true,
    distanceFromBaseKm: 2.5,
  },
  {
    id: 'jpr-city-palace',
    destinationId: 'jaipur',
    cityName: 'Jaipur',
    name: 'City Palace Jaipur',
    category: 'culture',
    description: 'Royal residence complex housing Chandra Mahal, Mubarak Mahal, and royal museums.',
    whyVisit: 'Intricate Peacock Gate, royal ceremonial costumes, weapons gallery, and silver urns.',
    image: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=800&q=80',
    coordinates: { lat: 26.9258, lng: 75.8237 },
    approxDurationMinutes: 120,
    bestTimeToVisit: 'Afternoon',
    openingHours: '09:30 AM',
    closingHours: '05:00 PM',
    estimatedTicketPrice: '₹200',
    isIndoor: true,
    distanceFromBaseKm: 2.1,
  },
  {
    id: 'jpr-jantar-mantar',
    destinationId: 'jaipur',
    cityName: 'Jaipur',
    name: 'Jantar Mantar (Observatory)',
    category: 'history',
    description: 'UNESCO World Heritage astronomical observation site built by Maharaja Sawai Jai Singh II.',
    whyVisit: "Features the world's largest stone sundial (Samrat Yantra) predicting accurate solar time.",
    image: 'https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=800&q=80',
    coordinates: { lat: 26.9248, lng: 75.8246 },
    approxDurationMinutes: 90,
    bestTimeToVisit: 'Morning',
    openingHours: '09:00 AM',
    closingHours: '05:00 PM',
    estimatedTicketPrice: '₹50',
    isIndoor: false,
    distanceFromBaseKm: 2.3,
  },
  {
    id: 'jpr-nahargarh-fort',
    destinationId: 'jaipur',
    cityName: 'Jaipur',
    name: 'Nahargarh Fort',
    category: 'history',
    description: 'Hilltop fort perched on the Aravalli Ridge overlooking Jaipur city, offering panoramic sunset views.',
    whyVisit: 'Explore the Madhavendra Bhawan, wax museum, and breathtaking sunset panorama of the Pink City.',
    image: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=800&q=80',
    coordinates: { lat: 26.9492, lng: 75.8076 },
    approxDurationMinutes: 120,
    bestTimeToVisit: 'Evening',
    openingHours: '10:00 AM',
    closingHours: '05:30 PM',
    estimatedTicketPrice: '₹50',
    isIndoor: false,
    distanceFromBaseKm: 5.8,
  },
  {
    id: 'jpr-albert-hall',
    destinationId: 'jaipur',
    cityName: 'Jaipur',
    name: 'Albert Hall Museum',
    category: 'history',
    description: 'Oldest museum of Rajasthan, built in Indo-Saracenic architectural style in 1887.',
    whyVisit: 'Rich collection of Rajasthani folk art, Egyptian mummy, carpets, pottery, and miniature paintings.',
    image: 'https://images.unsplash.com/photo-1566127444979-b3d2b654e3d7?auto=format&fit=crop&w=800&q=80',
    coordinates: { lat: 26.9102, lng: 75.8187 },
    approxDurationMinutes: 90,
    bestTimeToVisit: 'Afternoon',
    openingHours: '09:00 AM',
    closingHours: '05:00 PM',
    estimatedTicketPrice: '₹40 (Indians)',
    isIndoor: true,
    distanceFromBaseKm: 1.5,
  },
  {
    id: 'jpr-jal-mahal',
    destinationId: 'jaipur',
    cityName: 'Jaipur',
    name: 'Jal Mahal (Water Palace)',
    category: 'photography',
    description: 'Stunning 18th-century palace appearing to float in the middle of Man Sagar Lake.',
    whyVisit: 'Iconic photography spot for the palace reflected in still lake waters, especially at dawn and dusk.',
    image: 'https://images.unsplash.com/photo-1603262110263-fb0112e7cc33?auto=format&fit=crop&w=800&q=80',
    coordinates: { lat: 26.9596, lng: 75.8463 },
    approxDurationMinutes: 45,
    bestTimeToVisit: 'Morning',
    openingHours: 'Open 24 Hours (exterior viewing)',
    closingHours: 'Open 24 Hours',
    estimatedTicketPrice: 'Free Entry (exterior)',
    isIndoor: false,
    distanceFromBaseKm: 6.8,
  },

  // ─── DARJEELING (27.041°N, 88.2663°E) ───────────────────────────────────
  {
    id: 'darj-tiger-hill',
    destinationId: 'darjeeling',
    cityName: 'Darjeeling',
    name: 'Tiger Hill Sunrise Point',
    category: 'nature',
    description: 'Famous mountain summit offering panoramic views of Mount Kanchenjunga and Mount Everest at dawn.',
    whyVisit: 'Witness golden sun rays illuminating Kanchenjunga peaks in vivid orange and pink tones.',
    image: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=800&q=80',
    coordinates: { lat: 26.9961, lng: 88.2867 },
    approxDurationMinutes: 120,
    bestTimeToVisit: 'Morning',
    openingHours: '04:00 AM',
    closingHours: '07:00 AM',
    estimatedTicketPrice: '₹40 vehicle entry',
    isIndoor: false,
    distanceFromBaseKm: 11.5,
  },
  {
    id: 'darj-toy-train',
    destinationId: 'darjeeling',
    cityName: 'Darjeeling',
    name: 'Darjeeling Himalayan Railway (Toy Train)',
    category: 'culture',
    description: 'UNESCO World Heritage narrow-gauge steam train winding through tea estates and Batasia Loop.',
    whyVisit: 'Nostalgic mountain steam ride passing local street markets and breathtaking valley loops.',
    image: 'https://images.unsplash.com/photo-1563889362352-b0492c234f62?auto=format&fit=crop&w=800&q=80',
    coordinates: { lat: 27.0415, lng: 88.2631 },
    approxDurationMinutes: 120,
    bestTimeToVisit: 'Morning',
    openingHours: '09:00 AM',
    closingHours: '04:00 PM',
    estimatedTicketPrice: '₹1,000 – ₹1,500 (Steam Joy Ride)',
    isIndoor: false,
    distanceFromBaseKm: 0.5,
  },
  {
    id: 'darj-tea-garden',
    destinationId: 'darjeeling',
    cityName: 'Darjeeling',
    name: 'Happy Valley Tea Estate',
    category: 'nature',
    description: "One of Darjeeling's oldest tea gardens processing premium aromatic black tea since 1854.",
    whyVisit: 'Guided tea factory tour, tea tasting session, and walks amidst emerald tea bushes.',
    image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=800&q=80',
    coordinates: { lat: 27.0537, lng: 88.2678 },
    approxDurationMinutes: 90,
    bestTimeToVisit: 'Afternoon',
    openingHours: '08:00 AM',
    closingHours: '04:00 PM',
    estimatedTicketPrice: '₹100 factory tour',
    isIndoor: false,
    distanceFromBaseKm: 3.0,
  },
  {
    id: 'darj-batasia-loop',
    destinationId: 'darjeeling',
    cityName: 'Darjeeling',
    name: 'Batasia Loop & War Memorial',
    category: 'photography',
    description: 'Spectacular spiral railway loop where the toy train circles, offering 360° mountain panoramas.',
    whyVisit: 'Stunning viewpoint for Kanchenjunga, Gorkha war memorial, and the famous toy train spiral.',
    image: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=800&q=80',
    coordinates: { lat: 27.027, lng: 88.2594 },
    approxDurationMinutes: 60,
    bestTimeToVisit: 'Morning',
    openingHours: '06:00 AM',
    closingHours: '06:00 PM',
    estimatedTicketPrice: '₹20',
    isIndoor: false,
    distanceFromBaseKm: 5.0,
  },
  {
    id: 'darj-japanese-peace-pagoda',
    destinationId: 'darjeeling',
    cityName: 'Darjeeling',
    name: 'Japanese Peace Pagoda',
    category: 'religious',
    description: 'White-domed Buddhist pagoda built by Nipponzan Myōhōji movement on a hilltop above Darjeeling.',
    whyVisit: 'Serene meditation walks, golden Buddha statues, and sweeping Himalayan valley views.',
    image: 'https://images.unsplash.com/photo-1548625149-fc4a29cf7092?auto=format&fit=crop&w=800&q=80',
    coordinates: { lat: 27.0484, lng: 88.2536 },
    approxDurationMinutes: 60,
    bestTimeToVisit: 'Afternoon',
    openingHours: '04:30 AM',
    closingHours: '07:30 PM',
    estimatedTicketPrice: 'Free Entry',
    isIndoor: false,
    distanceFromBaseKm: 4.0,
  },

  // ─── GOA (North: 15.5438°N, 73.7554°E) ──────────────────────────────────
  {
    id: 'goa-calangute-beach',
    destinationId: 'goa-calangute',
    cityName: 'Goa',
    name: 'Calangute Beach & Water Sports',
    category: 'beach',
    description: '"Queen of Beaches" featuring golden sands, parasailing, jet skis, and lively beach shacks.',
    whyVisit: 'Thrilling water activities, seafood delicacies, ocean swimming, and vibrant beach atmosphere.',
    image: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=800&q=80',
    coordinates: { lat: 15.5438, lng: 73.7554 },
    approxDurationMinutes: 180,
    bestTimeToVisit: 'Morning',
    openingHours: 'Open 24 Hours',
    closingHours: 'Open 24 Hours',
    estimatedTicketPrice: 'Free Entry (Sports ₹500–₹2000)',
    isIndoor: false,
    distanceFromBaseKm: 0.2,
  },
  {
    id: 'goa-fort-aguada',
    destinationId: 'goa-calangute',
    cityName: 'Goa',
    name: 'Fort Aguada & Lighthouse',
    category: 'history',
    description: '17th-century Portuguese fortress and lighthouse guarding the mouth of the Mandovi River.',
    whyVisit: 'Sweeping panoramic views of the Arabian Sea, stone bastions, and historic lighthouse.',
    image: 'https://images.unsplash.com/photo-1587922546307-776227941871?auto=format&fit=crop&w=800&q=80',
    coordinates: { lat: 15.4924, lng: 73.7737 },
    approxDurationMinutes: 90,
    bestTimeToVisit: 'Evening',
    openingHours: '09:30 AM',
    closingHours: '06:00 PM',
    estimatedTicketPrice: '₹50',
    isIndoor: false,
    distanceFromBaseKm: 8.5,
  },
  {
    id: 'goa-bom-jesus',
    destinationId: 'goa-calangute',
    cityName: 'Goa',
    name: 'Basilica of Bom Jesus (Old Goa)',
    category: 'religious',
    description: 'UNESCO World Heritage church holding the sacred mortal remains of St. Francis Xavier.',
    whyVisit: 'Exquisite Baroque Portuguese architecture, marble flooring, and historical religious artwork.',
    image: 'https://images.unsplash.com/photo-1548625149-fc4a29cf7092?auto=format&fit=crop&w=800&q=80',
    coordinates: { lat: 15.5009, lng: 73.9116 },
    approxDurationMinutes: 90,
    bestTimeToVisit: 'Morning',
    openingHours: '09:00 AM',
    closingHours: '06:30 PM',
    estimatedTicketPrice: 'Free Entry',
    isIndoor: true,
    distanceFromBaseKm: 18.0,
  },
  {
    id: 'goa-anjuna-beach',
    destinationId: 'goa-calangute',
    cityName: 'Goa',
    name: 'Anjuna Beach & Flea Market',
    category: 'beach',
    description: 'Iconic bohemian beach famous for Wednesday flea markets, rocky coves, and trance parties.',
    whyVisit: 'Shop handicrafts, jewelry, and clothes at the vibrant flea market while enjoying the rocky beach.',
    image: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=800&q=80',
    coordinates: { lat: 15.5742, lng: 73.7443 },
    approxDurationMinutes: 150,
    bestTimeToVisit: 'Afternoon',
    openingHours: 'Open 24 Hours',
    closingHours: 'Open 24 Hours',
    estimatedTicketPrice: 'Free Entry',
    isIndoor: false,
    distanceFromBaseKm: 9.0,
  },
  {
    id: 'goa-vagator-beach',
    destinationId: 'goa-calangute',
    cityName: 'Goa',
    name: 'Vagator Beach & Chapora Fort',
    category: 'photography',
    description: 'Dramatic red-cliffed beach beneath the ruined Chapora Fort made famous by Bollywood.',
    whyVisit: 'Iconic sunset viewpoint from Chapora Fort walls overlooking the Arabian Sea and beach below.',
    image: 'https://images.unsplash.com/photo-1587922546307-776227941871?auto=format&fit=crop&w=800&q=80',
    coordinates: { lat: 15.6001, lng: 73.7362 },
    approxDurationMinutes: 120,
    bestTimeToVisit: 'Evening',
    openingHours: 'Open 24 Hours',
    closingHours: 'Open 24 Hours',
    estimatedTicketPrice: 'Free Entry',
    isIndoor: false,
    distanceFromBaseKm: 12.0,
  },
  {
    id: 'goa-dudhsagar-falls',
    destinationId: 'goa-calangute',
    cityName: 'Goa',
    name: 'Dudhsagar Falls (Day Trip)',
    category: 'nature',
    description: "India's 5th tallest waterfall, a four-tiered cascade on the Mandovi River at Goa-Karnataka border.",
    whyVisit: 'Breathtaking milky-white waterfall amid dense jungle; thrilling jeep safari and refreshing pool dip.',
    image: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=800&q=80',
    coordinates: { lat: 15.3147, lng: 74.3145 },
    approxDurationMinutes: 240,
    bestTimeToVisit: 'Morning',
    openingHours: '07:00 AM',
    closingHours: '04:00 PM',
    estimatedTicketPrice: '₹400 jeep safari + entry',
    isIndoor: false,
    distanceFromBaseKm: 58.0,
    isDayTrip: true,
  },

  // ─── MANALI (32.2432°N, 77.1892°E) ──────────────────────────────────────
  {
    id: 'mnl-solang-valley',
    destinationId: 'manali',
    cityName: 'Manali',
    name: 'Solang Valley Adventure Hub',
    category: 'adventure',
    description: 'High-altitude side valley famous for paragliding, zorbing, quad biking, and winter ski slopes.',
    whyVisit: 'Adrenaline adventure sports set against snowy mountain peaks and pine forests.',
    image: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=800&q=80',
    coordinates: { lat: 32.3164, lng: 77.1578 },
    approxDurationMinutes: 240,
    bestTimeToVisit: 'Morning',
    openingHours: '09:00 AM',
    closingHours: '05:00 PM',
    estimatedTicketPrice: 'Free Entry (Activities separate)',
    isIndoor: false,
    distanceFromBaseKm: 13.0,
  },
  {
    id: 'mnl-hadimba-temple',
    destinationId: 'manali',
    cityName: 'Manali',
    name: 'Hadimba Devi Temple',
    category: 'religious',
    description: 'Unique 1553 wooden pagoda temple nestled inside dense Dhungri cedar forests.',
    whyVisit: 'Intricate wood carvings, peaceful forest trails, yak rides, and ancient local legends.',
    image: 'https://images.unsplash.com/photo-1605649487212-47bdab064df7?auto=format&fit=crop&w=800&q=80',
    coordinates: { lat: 32.2483, lng: 77.1805 },
    approxDurationMinutes: 60,
    bestTimeToVisit: 'Morning',
    openingHours: '08:00 AM',
    closingHours: '06:00 PM',
    estimatedTicketPrice: 'Free Entry',
    isIndoor: false,
    distanceFromBaseKm: 2.0,
  },
  {
    id: 'mnl-rohtang-pass',
    destinationId: 'manali',
    cityName: 'Manali',
    name: 'Rohtang Pass (Day Trip)',
    category: 'nature',
    description: "High mountain pass at 3,978m on the eastern Pir Panjal Range of the Himalayas.",
    whyVisit: 'Snow-capped passes, glacier views, and the dramatic transition from Kullu valley to Lahaul.',
    image: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=800&q=80',
    coordinates: { lat: 32.3726, lng: 77.2527 },
    approxDurationMinutes: 300,
    bestTimeToVisit: 'Morning',
    openingHours: '06:00 AM',
    closingHours: '04:00 PM',
    estimatedTicketPrice: '₹550 permit + taxi',
    isIndoor: false,
    distanceFromBaseKm: 51.0,
    isDayTrip: true,
  },
  {
    id: 'mnl-old-manali',
    destinationId: 'manali',
    cityName: 'Manali',
    name: 'Old Manali & Manu Temple',
    category: 'culture',
    description: 'Charming village with cobbled lanes, backpacker cafes, apple orchards, and ancient Manu Rishi temple.',
    whyVisit: 'Stroll through riverside orchards, try apple crumble, and visit the ancient sage Manu temple.',
    image: 'https://images.unsplash.com/photo-1605649487212-47bdab064df7?auto=format&fit=crop&w=800&q=80',
    coordinates: { lat: 32.2637, lng: 77.1766 },
    approxDurationMinutes: 120,
    bestTimeToVisit: 'Afternoon',
    openingHours: 'Open 24 Hours',
    closingHours: 'Open 24 Hours',
    estimatedTicketPrice: 'Free Entry',
    isIndoor: false,
    distanceFromBaseKm: 3.5,
  },

  // ─── DIGHA (21.6266°N, 87.5074°E) ────────────────────────────────────────
  {
    id: 'digha-old-beach',
    destinationId: 'digha',
    cityName: 'Digha',
    name: 'Old Digha Sea Beach & Promenade',
    category: 'beach',
    description: 'Scenic concrete seawall lined with casual street food stalls, fish fry counters, and sea views.',
    whyVisit: 'Watch crashing waves against the stone embankments while tasting freshly fried pomfret and prawns.',
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80',
    coordinates: { lat: 21.6266, lng: 87.5074 },
    approxDurationMinutes: 120,
    bestTimeToVisit: 'Evening',
    openingHours: 'Open 24 Hours',
    closingHours: 'Open 24 Hours',
    estimatedTicketPrice: 'Free Entry',
    isIndoor: false,
    distanceFromBaseKm: 0.5,
  },
  {
    id: 'digha-new-beach',
    destinationId: 'digha',
    cityName: 'Digha',
    name: 'New Digha Beach',
    category: 'beach',
    description: 'Quieter, cleaner stretch of beach to the north of Old Digha, popular for sunrise walks.',
    whyVisit: 'Peaceful morning walks along the shore, sunrise photography, and fresh coconut water.',
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80',
    coordinates: { lat: 21.6327, lng: 87.5123 },
    approxDurationMinutes: 90,
    bestTimeToVisit: 'Morning',
    openingHours: 'Open 24 Hours',
    closingHours: 'Open 24 Hours',
    estimatedTicketPrice: 'Free Entry',
    isIndoor: false,
    distanceFromBaseKm: 1.2,
  },
  {
    id: 'digha-marine-aquarium',
    destinationId: 'digha',
    cityName: 'Digha',
    name: 'Marine Aquarium & Regional Centre (MARC)',
    category: 'family',
    description: "Asia's largest salt-water marine aquarium housing diverse sea creatures, sharks, and rays.",
    whyVisit: 'Educational marine life exhibits including sea snakes, lobsters, rays, and coastal ecology displays.',
    image: 'https://images.unsplash.com/photo-1522069169874-c58ec4b76be5?auto=format&fit=crop&w=800&q=80',
    coordinates: { lat: 21.6295, lng: 87.5142 },
    approxDurationMinutes: 90,
    bestTimeToVisit: 'Afternoon',
    openingHours: '09:30 AM',
    closingHours: '06:00 PM',
    estimatedTicketPrice: 'Free Entry',
    isIndoor: true,
    distanceFromBaseKm: 1.2,
  },
  {
    id: 'digha-amrabati-park',
    destinationId: 'digha',
    cityName: 'Digha',
    name: 'Amrabati Park & Children Area',
    category: 'family',
    description: 'Well-maintained public park near the seafront with children rides, gardens, and recreational facilities.',
    whyVisit: 'Ideal for families with children; beautiful flower gardens, toy train, and peaceful greenery by the sea.',
    image: 'https://images.unsplash.com/photo-1519331379826-f10be5486c6f?auto=format&fit=crop&w=800&q=80',
    coordinates: { lat: 21.6275, lng: 87.5090 },
    approxDurationMinutes: 60,
    bestTimeToVisit: 'Evening',
    openingHours: '08:00 AM',
    closingHours: '07:00 PM',
    estimatedTicketPrice: '₹10',
    isIndoor: false,
    distanceFromBaseKm: 0.8,
  },
  {
    id: 'digha-sea-shore-temple',
    destinationId: 'digha',
    cityName: 'Digha',
    name: 'Kapilmuni Ashram & Sea Shore Temple',
    category: 'religious',
    description: 'Ancient ashram of the sage Kapilmuni at the confluence of the sea, of mythological significance.',
    whyVisit: 'Spiritual sunrise rituals, ancient legends of sage Kapilmuni, and sacred bathing ghat.',
    image: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=800&q=80',
    coordinates: { lat: 21.6241, lng: 87.5065 },
    approxDurationMinutes: 45,
    bestTimeToVisit: 'Morning',
    openingHours: '05:00 AM',
    closingHours: '08:00 PM',
    estimatedTicketPrice: 'Free Entry',
    isIndoor: false,
    distanceFromBaseKm: 0.7,
  },
  {
    id: 'digha-shankarpur-beach',
    destinationId: 'digha',
    cityName: 'Digha',
    name: 'Shankarpur Beach (Day Trip)',
    category: 'beach',
    description: 'Serene, uncrowded fishing village beach 13km from Digha with casuarina groves and fishing boats.',
    whyVisit: 'Peaceful getaway from crowded Digha; watch fishermen haul nets and enjoy pristine shoreline.',
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80',
    coordinates: { lat: 21.6544, lng: 87.5723 },
    approxDurationMinutes: 120,
    bestTimeToVisit: 'Morning',
    openingHours: 'Open 24 Hours',
    closingHours: 'Open 24 Hours',
    estimatedTicketPrice: 'Free Entry',
    isIndoor: false,
    distanceFromBaseKm: 13.0,
    isDayTrip: true,
  },
  {
    id: 'digha-tajpur-beach',
    destinationId: 'digha',
    cityName: 'Digha',
    name: 'Tajpur Beach (Day Trip)',
    category: 'nature',
    description: 'Untouched beach surrounded by dense casuarina forests and red crab colonies, 17km from Digha.',
    whyVisit: 'Pristine natural beach with unique red crabs, dense pine forest walks, and tranquil seascape.',
    image: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=800&q=80',
    coordinates: { lat: 21.6711, lng: 87.5877 },
    approxDurationMinutes: 150,
    bestTimeToVisit: 'Morning',
    openingHours: 'Open 24 Hours',
    closingHours: 'Open 24 Hours',
    estimatedTicketPrice: 'Free Entry',
    isIndoor: false,
    distanceFromBaseKm: 17.0,
    isDayTrip: true,
  },
  {
    id: 'digha-mandarmani',
    destinationId: 'digha',
    cityName: 'Digha',
    name: 'Mandarmani Beach (Day Trip)',
    category: 'beach',
    description: "India's longest motorable beach, 21km from Digha, known for red crabs and casuarina groves.",
    whyVisit: 'Drive on the beach, spot red land crabs at dawn, and enjoy its raw natural coastal beauty.',
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80',
    coordinates: { lat: 21.6667, lng: 87.5167 },
    approxDurationMinutes: 180,
    bestTimeToVisit: 'Morning',
    openingHours: 'Open 24 Hours',
    closingHours: 'Open 24 Hours',
    estimatedTicketPrice: 'Free Entry',
    isIndoor: false,
    distanceFromBaseKm: 21.0,
    isDayTrip: true,
  },

  // ─── PURI (19.8135°N, 85.8312°E) ─────────────────────────────────────────
  {
    id: 'puri-jagannath-temple',
    destinationId: 'puri',
    cityName: 'Puri',
    name: 'Jagannath Temple',
    category: 'religious',
    description: 'One of the four sacred Char Dham pilgrimage sites of Hinduism, dedicated to Lord Jagannath.',
    whyVisit: 'Witness the magnificent 65-meter Deula architecture, sacred rituals, and the famous Rath Yatra traditions.',
    image: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=800&q=80',
    coordinates: { lat: 19.8047, lng: 85.8181 },
    approxDurationMinutes: 120,
    bestTimeToVisit: 'Morning',
    openingHours: '05:00 AM',
    closingHours: '11:00 PM',
    estimatedTicketPrice: 'Free Entry (Hindus only)',
    isIndoor: false,
    distanceFromBaseKm: 1.2,
  },
  {
    id: 'puri-beach',
    destinationId: 'puri',
    cityName: 'Puri',
    name: 'Puri Sea Beach',
    category: 'beach',
    description: 'One of the most popular beaches on the Bay of Bengal, with golden sand, fishing boats, and surfers.',
    whyVisit: 'Morning sunrise walks, watch traditional fishermen in action, and vibrant beach activity.',
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80',
    coordinates: { lat: 19.7998, lng: 85.8351 },
    approxDurationMinutes: 120,
    bestTimeToVisit: 'Morning',
    openingHours: 'Open 24 Hours',
    closingHours: 'Open 24 Hours',
    estimatedTicketPrice: 'Free Entry',
    isIndoor: false,
    distanceFromBaseKm: 0.5,
  },
  {
    id: 'puri-konark-temple',
    destinationId: 'puri',
    cityName: 'Puri',
    name: 'Konark Sun Temple (Day Trip)',
    category: 'history',
    description: 'UNESCO World Heritage 13th-century temple shaped like a giant stone chariot dedicated to the Sun god.',
    whyVisit: 'Marvel at the intricate erotic sculptures, colossal stone wheels, and 700-year-old Odisha craftsmanship.',
    image: 'https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=800&q=80',
    coordinates: { lat: 19.8877, lng: 86.0947 },
    approxDurationMinutes: 180,
    bestTimeToVisit: 'Morning',
    openingHours: '06:00 AM',
    closingHours: '08:00 PM',
    estimatedTicketPrice: '₹40 (Indians) / ₹600 (Foreigners)',
    isIndoor: false,
    distanceFromBaseKm: 35.0,
    isDayTrip: true,
  },
  {
    id: 'puri-chilika-lake',
    destinationId: 'puri',
    cityName: 'Puri',
    name: 'Chilika Lake Bird Sanctuary (Day Trip)',
    category: 'nature',
    description: "Asia's largest brackish water lagoon and Ramsar wetland site with migratory birds and Irrawaddy dolphins.",
    whyVisit: 'Spot flamingos, pelicans, rare Irrawaddy dolphins, and sail through the stunning lake ecosystem.',
    image: 'https://images.unsplash.com/photo-1519331379826-f10be5486c6f?auto=format&fit=crop&w=800&q=80',
    coordinates: { lat: 19.7213, lng: 85.3162 },
    approxDurationMinutes: 240,
    bestTimeToVisit: 'Morning',
    openingHours: '06:00 AM',
    closingHours: '05:00 PM',
    estimatedTicketPrice: '₹200 boat ride',
    isIndoor: false,
    distanceFromBaseKm: 55.0,
    isDayTrip: true,
  },
  {
    id: 'puri-swargadwar-beach',
    destinationId: 'puri',
    cityName: 'Puri',
    name: 'Swargadwar Beach & Cremation Ghat',
    category: 'culture',
    description: 'Sacred cremation ground beside the sea where moksha (liberation) rituals have been performed for centuries.',
    whyVisit: 'Deeply spiritual atmosphere; witness Hindu last rites traditions unique to this sacred coastal pilgrimage town.',
    image: 'https://images.unsplash.com/photo-1608979048467-315ef9229f3a?auto=format&fit=crop&w=800&q=80',
    coordinates: { lat: 19.8006, lng: 85.8273 },
    approxDurationMinutes: 45,
    bestTimeToVisit: 'Evening',
    openingHours: 'Open 24 Hours',
    closingHours: 'Open 24 Hours',
    estimatedTicketPrice: 'Free Entry',
    isIndoor: false,
    distanceFromBaseKm: 1.0,
  },
  {
    id: 'puri-sand-art-museum',
    destinationId: 'puri',
    cityName: 'Puri',
    name: 'Sand Art Museum',
    category: 'culture',
    description: 'Gallery showcasing the world-class sand sculptures of Sudarshan Patnaik and other Odisha sand artists.',
    whyVisit: 'Witness intricate large-scale sand art and sculptures depicting Hindu mythology and social themes.',
    image: 'https://images.unsplash.com/photo-1566127444979-b3d2b654e3d7?auto=format&fit=crop&w=800&q=80',
    coordinates: { lat: 19.8010, lng: 85.8300 },
    approxDurationMinutes: 60,
    bestTimeToVisit: 'Afternoon',
    openingHours: '10:00 AM',
    closingHours: '06:00 PM',
    estimatedTicketPrice: '₹30',
    isIndoor: true,
    distanceFromBaseKm: 0.8,
  },

  // ─── UDAIPUR (24.5854°N, 73.7125°E) ──────────────────────────────────────
  {
    id: 'udp-city-palace',
    destinationId: 'udaipur',
    cityName: 'Udaipur',
    name: 'City Palace Udaipur',
    category: 'history',
    description: 'Magnificent Rajput palace complex overlooking Lake Pichola, built over 400 years by Mewar rulers.',
    whyVisit: 'Explore 11 interconnected palaces, mosaic balconies, crystal gallery, and panoramic lake views.',
    image: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=800&q=80',
    coordinates: { lat: 24.5761, lng: 73.6816 },
    approxDurationMinutes: 180,
    bestTimeToVisit: 'Morning',
    openingHours: '09:30 AM',
    closingHours: '05:30 PM',
    estimatedTicketPrice: '₹300 (Indians)',
    isIndoor: true,
    distanceFromBaseKm: 2.8,
  },
  {
    id: 'udp-lake-pichola',
    destinationId: 'udaipur',
    cityName: 'Udaipur',
    name: 'Lake Pichola Boat Ride',
    category: 'nature',
    description: 'Artificial lake built in 1362, offering romantic sunset boat rides past island palaces.',
    whyVisit: 'Glide past the famous Lake Palace hotel, Jag Mandir island, and golden city palace reflections.',
    image: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=800&q=80',
    coordinates: { lat: 24.5726, lng: 73.6801 },
    approxDurationMinutes: 90,
    bestTimeToVisit: 'Evening',
    openingHours: '08:00 AM',
    closingHours: '06:00 PM',
    estimatedTicketPrice: '₹400 boat ride',
    isIndoor: false,
    distanceFromBaseKm: 2.5,
  },
  {
    id: 'udp-sajjangarh-palace',
    destinationId: 'udaipur',
    cityName: 'Udaipur',
    name: 'Sajjangarh Palace (Monsoon Palace)',
    category: 'photography',
    description: 'Hilltop palace built to observe monsoon clouds, now offering 360° panoramic views of Udaipur.',
    whyVisit: 'Stunning sunset panoramas across the city, lakes, and Aravalli hills; magical during monsoon.',
    image: 'https://images.unsplash.com/photo-1603262110263-fb0112e7cc33?auto=format&fit=crop&w=800&q=80',
    coordinates: { lat: 24.5699, lng: 73.6520 },
    approxDurationMinutes: 90,
    bestTimeToVisit: 'Evening',
    openingHours: '08:00 AM',
    closingHours: '06:00 PM',
    estimatedTicketPrice: '₹65 + ₹65 video camera',
    isIndoor: false,
    distanceFromBaseKm: 5.0,
  },
  {
    id: 'udp-jag-mandir',
    destinationId: 'udaipur',
    cityName: 'Udaipur',
    name: 'Jag Mandir Island Palace',
    category: 'history',
    description: 'Island palace in the middle of Lake Pichola, once sheltering Mughal Prince Khurram (Shah Jahan).',
    whyVisit: 'Ornate Rajput garden palace with elephant statues, lily ponds, and lakeside fine dining.',
    image: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=800&q=80',
    coordinates: { lat: 24.5695, lng: 73.6769 },
    approxDurationMinutes: 120,
    bestTimeToVisit: 'Afternoon',
    openingHours: '10:00 AM',
    closingHours: '06:00 PM',
    estimatedTicketPrice: '₹300 including boat',
    isIndoor: false,
    distanceFromBaseKm: 3.2,
  },
  {
    id: 'udp-fateh-sagar-lake',
    destinationId: 'udaipur',
    cityName: 'Udaipur',
    name: 'Fateh Sagar Lake & Nehru Park',
    category: 'nature',
    description: 'Picturesque artificial lake with three islands including Nehru Park and Solar Observatory.',
    whyVisit: 'Boat rides to Nehru Island, lakeside evening walks, and stunning Aravalli Hills backdrop.',
    image: 'https://images.unsplash.com/photo-1519331379826-f10be5486c6f?auto=format&fit=crop&w=800&q=80',
    coordinates: { lat: 24.5978, lng: 73.6781 },
    approxDurationMinutes: 90,
    bestTimeToVisit: 'Evening',
    openingHours: '08:00 AM',
    closingHours: '06:00 PM',
    estimatedTicketPrice: '₹30 boat',
    isIndoor: false,
    distanceFromBaseKm: 3.5,
  },
  {
    id: 'udp-bagore-ki-haveli',
    destinationId: 'udaipur',
    cityName: 'Udaipur',
    name: 'Bagore Ki Haveli Museum',
    category: 'culture',
    description: 'Restored 18th-century haveli with 138 rooms housing costumes, puppets, and folk art collections.',
    whyVisit: 'Rajasthani folk dance and music performances every evening in the haveli courtyard.',
    image: 'https://images.unsplash.com/photo-1566127444979-b3d2b654e3d7?auto=format&fit=crop&w=800&q=80',
    coordinates: { lat: 24.5745, lng: 73.6836 },
    approxDurationMinutes: 90,
    bestTimeToVisit: 'Evening',
    openingHours: '10:00 AM',
    closingHours: '08:00 PM',
    estimatedTicketPrice: '₹60 museum + ₹90 show',
    isIndoor: true,
    distanceFromBaseKm: 1.5,
  },
];

// ---------------------------------------------------------------------------
// COORDINATE-BASED DESTINATION LOOKUP
// This is the CRITICAL FIX: places are matched by haversine distance from
// the destination coordinates, not by text string matching.
// ---------------------------------------------------------------------------

/**
 * Primary filter: Get all curated places within the geographic radius of a destination.
 * Distance is calculated using the Haversine formula from destination coordinates.
 * Text name is used only as a SECONDARY hint, never as the primary filter.
 */
export async function getPlacesForDestination(
  destName: string,
  coords?: LocationCoordinates
): Promise<TouristPlace[]> {

  // ── STEP 1: Coordinate-based filtering (PRIMARY — THE CRITICAL FIX) ──────
  if (coords && coords.lat !== 0 && coords.lng !== 0) {
    const destObj = { lat: coords.lat, lng: coords.lng, name: destName };
    const validated = filterAttractionsForDestination(destObj, CURATED_TOURIST_PLACES);

    if (validated.length >= 2) {
      console.info(
        `[TourismService] ✅ ${validated.length} verified places for "${destName}" via coordinate filter.`
      );
      return validated;
    }

    // ── STEP 2: Try Overpass API for unknown/less-common destinations ─────
    try {
      const dynamicPlaces = await fetchOverpassPlaces(coords, destName);
      if (dynamicPlaces.length > 0) {
        const destType = resolveDestinationType(destName);
        const validatedDynamic = filterAttractionsForDestination(destObj, dynamicPlaces, destType);
        if (validatedDynamic.length > 0) {
          console.info(`[TourismService] ✅ ${validatedDynamic.length} Overpass-verified places for "${destName}".`);
          return validatedDynamic;
        }
        // Return un-filtered dynamic places if all within overpass radius (they already are)
        console.info(`[TourismService] Using all ${dynamicPlaces.length} Overpass places for "${destName}".`);
        return dynamicPlaces;
      }
    } catch (err) {
      console.warn('[TourismService] Overpass API unavailable, using curated fallback:', err);
    }

    // ── STEP 3: No attractions found — return empty (NOT a different city's data) ─
    console.warn(`[TourismService] ⚠️ No verified attractions found for "${destName}" at [${coords.lat}, ${coords.lng}].`);
    return [];
  }

  // ── FALLBACK: No coordinates available — use name hint only for popular preloaded ──
  // This should only occur when coords are genuinely missing (no geocoding yet)
  const normName = destName.toLowerCase().trim();
  const nameHint = CURATED_TOURIST_PLACES.filter(
    (place) =>
      place.destinationId?.toLowerCase() === normName ||
      place.cityName.toLowerCase() === normName ||
      place.destinationId?.toLowerCase().startsWith(normName) ||
      normName.startsWith(place.destinationId?.toLowerCase() || '__none__')
  );

  if (nameHint.length > 0) {
    console.warn(`[TourismService] ⚠️ Using name-only hint for "${destName}" — no coords provided.`);
    return nameHint;
  }

  return [];
}

// ---------------------------------------------------------------------------
// OpenStreetMap Overpass API — live place data for any destination
// ---------------------------------------------------------------------------
async function fetchOverpassPlaces(
  coords: LocationCoordinates,
  cityName: string
): Promise<TouristPlace[]> {
  const radius = 8000; // 8km radius around destination center
  const query = `
    [out:json][timeout:12];
    (
      node["tourism"~"attraction|museum|viewpoint|gallery|theme_park"](around:${radius},${coords.lat},${coords.lng});
      node["historic"~"monument|castle|fort|memorial|archaeological_site"](around:${radius},${coords.lat},${coords.lng});
      node["leisure"~"park|water_park|beach"](around:${radius},${coords.lat},${coords.lng});
      node["amenity"~"place_of_worship"](around:${radius},${coords.lat},${coords.lng});
    );
    out body 15;
  `;

  const url = `https://overpass-api.de/api/interpreter?data=${encodeURIComponent(query)}`;
  const response = await fetch(url);
  if (!response.ok) throw new Error('Overpass API network response failed');

  const data = await response.json();
  if (!data.elements || data.elements.length === 0) return [];

  const places: TouristPlace[] = data.elements
    .filter((el: any) => el.tags && el.tags.name && el.lat && el.lon)
    .slice(0, 12)
    .map((el: any) => {
      const tags = el.tags;
      const isMuseum = tags.tourism === 'museum' || tags.historic === 'monument';
      const isPark = tags.leisure === 'park' || tags.tourism === 'viewpoint';
      const isBeach = tags.leisure === 'beach' || tags.natural === 'beach';
      const isTemple = tags.amenity === 'place_of_worship';

      let cat: PlaceCategory = 'culture';
      if (isMuseum) cat = 'history';
      else if (isBeach) cat = 'beach';
      else if (isPark) cat = 'nature';
      else if (isTemple) cat = 'religious';
      else if (tags.historic) cat = 'history';

      const distKm = parseFloat(
        haversineDistance(coords.lat, coords.lng, el.lat, el.lon).toFixed(1)
      );

      return {
        id: `osm-${el.id}`,
        destinationId: cityName.toLowerCase().replace(/\s+/g, '-'),
        cityName,
        name: tags.name,
        category: cat,
        description:
          tags.description ||
          tags['description:en'] ||
          `Prominent local ${tags.tourism || tags.historic || tags.leisure || 'attraction'} in ${cityName}.`,
        whyVisit: `Popular landmark in ${cityName}, verified via OpenStreetMap community data.`,
        image: 'https://images.unsplash.com/photo-1488646953014-85cb44e25828?auto=format&fit=crop&w=800&q=80',
        coordinates: { lat: el.lat, lng: el.lon },
        approxDurationMinutes: isMuseum ? 120 : isBeach ? 150 : 60,
        bestTimeToVisit: isBeach ? 'Morning' : isPark ? 'Evening' : 'Morning',
        openingHours: tags.opening_hours || 'Check local hours',
        isIndoor: isMuseum,
        distanceFromBaseKm: distKm,
      };
    });

  return places;
}

// ---------------------------------------------------------------------------
// Places Near User's Current Location
// ---------------------------------------------------------------------------
export async function getPlacesNearLocation(
  userCoords: LocationCoordinates,
  categoryFilter?: string
): Promise<TouristPlace[]> {
  try {
    const livePlaces = await fetchOverpassPlaces(userCoords, 'Your Location');
    if (livePlaces.length > 0) {
      if (categoryFilter && categoryFilter !== 'all') {
        return livePlaces.filter((p) => p.category === categoryFilter);
      }
      return livePlaces;
    }
  } catch (err) {
    console.warn('Live near-me fetch failed, returning closest curated places:', err);
  }
  // Closest 6 from curated dataset as absolute fallback
  return CURATED_TOURIST_PLACES.slice(0, 6);
}
